### ISSUE TITLE
Lints included libraries

### ISSUE THREAD

**Issue by danpantry** [brunch/jshint-brunch#16]
Hi,

I love jshint and it's application with brunch, really lightweight - unfortunately, jshint-brunch will lint all included files if you do not specify a path, which includes files included by 3rd party libraries (for example, through npm or bower). This is a problem because some libraries (such as auto-reload-brunch) are not in strict mode, but I would like to enforce my front end code to be strict compliant.

I appreciate I could use a path, but it's still unexpected behaviour and I thought I would bring it to your attention.

**Comment by es128** [comment]
Yeah seems like a bug based on this line in the README

> By default, only files in your config.paths.app are linted.
