### ISSUE TITLE
Disable jshint in Production environments

### ISSUE THREAD

**Issue by jualoppaz** [brunch/jshint-brunch#29]
Hi!

Is there any option for disable jshint validations in Production environments?

I build my brunch apps with **brunch build --production** command and I can't find a way for do this in a Production environment like Heroku.

Thank you so much.

**Comment by paulmillr** [comment]
see config.overrides on the official docs

```
overrides: {
  production: {
    plugins: {off: ['jshint-brunch',]}
  }
}
```

**Comment by jualoppaz** [comment]
Thank you so much, @paulmillr .

I didn't see that option.
